import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { withSSRContext } from 'aws-amplify';
import { listParks } from '../src/graphql/queries';
import { AmplifyS3Image } from '@aws-amplify/ui-react';

export async function getServerSideProps () {
  let SSR = withSSRContext() 
  const { data } = await SSR.API.graphql({
    query: listParks,
  })
  return {
    props: {
      parks: data.listParks.items
    }
  }
}

export default function Home({parks}) {
  console.log(parks)
  return (
    <div className={styles.container}>
      <Head>
        <title>National Parks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>
          National Parks <Link href="/create-park">(+)</Link>
        </h1>
        <div className="image-grid">
          {parks.map(park => {
            return (
              <div key={park.id} className="image-grid__item">
                <h2>{park.name}</h2>
                <AmplifyS3Image imgKey={park.image.key} height='220px' />
              </div>
            )
          })}
        </div>
      </div>
    </div>
  );
}
